// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBypfSchfgIWKoNmgITrLXwZsg7hgUniVA',
    appId: '1:595295320318:web:7707eaba77fa9bf37b8daf',
    messagingSenderId: '595295320318',
    projectId: 'arabian-majlis-petta',
    authDomain: 'arabian-majlis-petta.firebaseapp.com',
    storageBucket: 'arabian-majlis-petta.firebasestorage.app',
    measurementId: 'G-DJRX43LKT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYBm5artqfSJ0Ibaz1B9Aq60IQvg1yf4k',
    appId: '1:595295320318:android:7570d4c7324dfccf7b8daf',
    messagingSenderId: '595295320318',
    projectId: 'arabian-majlis-petta',
    storageBucket: 'arabian-majlis-petta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPHsJN49AR9ezH6JLfypZzAdBXnJrX_Gk',
    appId: '1:595295320318:ios:6cb1a7b413ba46b67b8daf',
    messagingSenderId: '595295320318',
    projectId: 'arabian-majlis-petta',
    storageBucket: 'arabian-majlis-petta.firebasestorage.app',
    iosBundleId: 'com.example.arabianMajlisPetta',
  );
}
